### ISSUE TITLE
Add Installation Instructions

### ISSUE THREAD

**Issue by Neurrone** [wiresong/sonica#1]
I'd love to try this extension. However, I'm not able to figure out how to install it, and all the instructions I've been able to find tell me to go to the Vs Code marketplace.

**Comment by ahicks92** [comment]
Just search through Sonica in the VSCode extensions thing and it's right there.

@wiresong probably worth adding a direct link.

**Comment by wiresong** [comment]
Hi,

I thought I added an installation section to the readme, but apparently not. My bad.

I just added it now, but in general it's what @ahicks92 said-open the extensions view in VSCode (with ctrl+shift+x, or search for "view: show extensions" in the command pallet) and then search for Sonica. (Alternatively just use the direct link in the Readme.)

**Comment by Neurrone** [comment]
Thanks, I didn't realize it was on the marketplace.
